export {default as Navbar} from './Navbar.jsx'
export {default as Hero} from './Hero.jsx'
export {default as Company_logo} from './Company_logo.jsx'
export {default as Purpose_sec} from './Purpose_sec.jsx'
export {default as Schedule_sec} from './Schedule_sec.jsx'
export {default as Monitor} from './Monitor.jsx'